
CREATE DATABASE IF NOT EXISTS RAINFALL_AGRI_DB;
USE DATABASE RAINFALL_AGRI_DB;

//drop database RAINFALL_AGRI_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
USE SCHEMA RAW;


CREATE OR REPLACE TABLE RAINFALL_AGRI_DATA (
    YEAR            INT,
    LOCATION        VARCHAR(100),
    AREA            INT,
    RAINFALL        NUMBER(10,2),
    TEMPERATURE     NUMBER(10,2),
    SOIL_TYPE       VARCHAR(100),
    IRRIGATION      VARCHAR(100),
    YIELDS          INT,
    HUMIDITY        NUMBER(5,2),
    CROPS           VARCHAR(100),
    PRICE           NUMBER(12,2),
    SEASON          VARCHAR(50)
);

SELECT * FROM RAINFALL_AGRI_DATA;