
CREATE OR REPLACE STAGE RAINFALL_AGRI_DB.RAW.RAINFALL_AGRI_STAGE
    URL = 's3://<AWS_S3_bucket>/'
    STORAGE_INTEGRATION = RAINFALL_AGRI_S3_INTEGRATION;


DESC STAGE RAINFALL_AGRI_DB.RAW.RAINFALL_AGRI_STAGE;


LIST @RAINFALL_AGRI_DB.RAW.RAINFALL_AGRI_STAGE;
