USE DATABASE RAINFALL_AGRI_DB;
USE SCHEMA RAW;


-- Create a file format object 
CREATE OR REPLACE FILE FORMAT RAINFALL_AGRI_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

COPY INTO RAINFALL_AGRI_DATA
FROM @RAINFALL_AGRI_DB.RAW.RAINFALL_AGRI_STAGE
FILE_FORMAT = (
    FORMAT_NAME = RAINFALL_AGRI_CSV_FORMAT
)
ON_ERROR = 'CONTINUE';

LIST @RAINFALL_AGRI_DB.RAW.RAINFALL_AGRI_STAGE;

SELECT *
FROM RAINFALL_AGRI_DATA;

SELECT DISTINCT YEAR FROM RAINFALL_AGRI_DATA;


-- Define the CSV format directly in COPY INTO
-- You can skip creating the file-format object:
/*
COPY INTO RAINFALL_AGRI_DATA
FROM @RAINFALL_AGRI_STAGE
FILE_FORMAT = (
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
)
ON_ERROR = 'CONTINUE';
*/