-- prepare data in snowflake

USE DATABASE RAINFALL_AGRI_DB;
USE SCHEMA RAW;

SELECT * FROM RAINFALL_AGRI_DATA;

SELECT COUNT(*) FROM RAINFALL_AGRI_DATA;

SELECT YEAR, COUNT(*) FROM RAINFALL_AGRI_DATA
GROUP BY YEAR 
ORDER BY YEAR ASC;